### ISSUE TITLE
Bimodal threshold as Mean?

### ISSUE THREAD

**Issue by zvezdochiot** [mauvilsa/imgtxtenh#11]
Bimodal threshold according to the histogram:
https://github.com/mauvilsa/imgtxtenh/blob/9a5113db63220a1e947d1a5690025b4b0c73698a/src/imgconv.c#L58-L69
when used as `minval` in:
https://github.com/mauvilsa/imgtxtenh/blob/9a5113db63220a1e947d1a5690025b4b0c73698a/src/intimg.c#L439
gives good results on pages with images.

Maybe you should consider replacing `minval` with various options?

Bimodal threshold:
```c
int threshold_bimodal_graym (gray** img, gray** alph, int imgW, int imgH)
{
  int k, hist[256];
  int cnt = hist_graym(img,alph,imgW,imgH,hist);
  float T, Tw, Tb, Tn, iw, ib;
  int threshold = 0;

  T = 0.5 * 256;
  Tn = 0;
  while ( T != Tn )
  {
    Tn = T;
    Tb = Tw = ib = iw = 0;
    for (k = 0; k < 256; k++)
    {
      if ( k > T)
      {
        Tw += (k * hist[k]);
        iw += hist[k];
      } else {
        Tb += (k * hist[k]);
        ib += hist[k];
      }
    }
    if (iw == 0 && ib == 0)
    {
      T = Tn;
    } else if (iw == 0) {
      T = Tb/ib;
    } else if (ib == 0) {
      T = Tw/iw;
    } else {
      T = ((Tw / iw) + (Tb / ib)) * 0.5;
    }
  }
  threshold = (int)(T + 0.5);

  return threshold;
}
```

**Comment by mauvilsa** [comment]
@zvezdochiot I am not actively developing this tool. You are welcome create a pull request. The only requirement is that with all the current options the tool should do exactly the same process. Several people use this tool, so I wouldn't accept a pull request that could change the original behavior.
