### ISSUE TITLE
How to read many images and how to use with python

### ISSUE THREAD

**Issue by chuan298** [mauvilsa/imgtxtenh#12]

**Comment by mauvilsa** [comment]
The tool only supports processing one image per call. If you want to process many images just create a loop in a shell script. If you need more efficiency you could parallelize for example using GNU parallel.

The tool itself is a single command line tool, not a library or including a python wrapper. You could call from python the tool for example using popen. Alternatively there is kind of a successor to imgtxtenh which is a library and has a python wrapper. However, there are a few differences with respect to imgtxtenh, it is not well documented and it is not available to install from pypi. So you need to build it yourself. You can find the source code at https://github.com/omni-us/pagexml/tree/master/py-textfeat and the automatically generated API documentation at https://omni-us.github.io/pagexml/py-textfeat/.

**Comment by chuan298** [comment]
thank you very much
