### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by aarora8** [mauvilsa/imgtxtenh#2]
Hi I am new to this,
I would be highly grateful if you can please share steps to install it.
Thanks

**Comment by mauvilsa** [comment]
In the readme there is already a section that explains how to compile the tool (https://github.com/mauvilsa/imgtxtenh#user-content-compilation). It is the usual cmake compilation procedure. With that you get the imgtxtenh binary. When running the cmake command you will see what prerequisites are required to compile. Installing the tool is optional. You can do "make install" as is standard with makefiles or you can copy it to any location you prefer.

**Comment by trangtran0602** [comment]
Hi all, 
I have a project need to use your imgtxtenh. I installed successfully, but I don't know to enter something. Example: imgtxtenh -N <input image>, and it display: term-256colorxterm-256colorxterm-256color. In this case, what will I enter?
Thank you very much!

**Comment by mauvilsa** [comment]
@trangtran0602 I guess you must have some problem in the configuration of your terminal which is not related to imgtxtenh.
