### ISSUE TITLE
Suspected bug when using default parameters but changing units to mm

### ISSUE THREAD

**Issue by jpuigcerver** [mauvilsa/imgtxtenh#3]
I suspect there is a bug in the tool when one uses the default parameter values (set in pixels), but decides to change the units in mm to specify some other parameter.

In particular, I think this line is problematic: https://github.com/mauvilsa/imgtxtenh/blob/5cca7892b7174748f8e0576fe0f832660c8c273d/imgtxtenh.c#L281

The `if' block is used to convert the units set by the user in mm to pixels. However, the problem is that if the user only specifies some values in mm and relies on the default values in pixels, the conversion is applied anyway, which messes everything up.

**Comment by mauvilsa** [comment]
I have committed some changes to resolve this. Now both units have independent default values. So, depending on which units the users chooses, the respective default values would be used.
