### ISSUE TITLE
I can't install imgtxtenh

### ISSUE THREAD

**Issue by zengqi0730** [mauvilsa/imgtxtenh#8]
zengqi@zengqi:~$ convert -version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib

When i compile imgtxtenh:
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make

when making... error comes out:
undefined reference to ‘DestroyPixelWand’
undefined reference to 'xxx' and so on

Could you help me?

**Comment by zengqi0730** [comment]
I solved:
reinstall the imagemagick6
sudo make uninstall   (I compiled and installed ImageMagick exact from ImageMagick-6.9.10-60.zip, the same way to  imagemagick7)
download zip or clone from https://github.com/ImageMagick/ImageMagick6
unzip and cd
./configure --with-modules --enable-shared --with-perl --with-magick-plus-plus --enable-lzw
make 
sudo make install 
sudo ldconfig /usr/local/lib
/usr/local/bin/convert logo: logo.gif
make check
conver -version
----------------------------------------
download imgtxtenh-master.zip and exact
cd imgtxtenh-master
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
make
sudo make install
----------------------------------------------
zengqi@zengqi:~/imgtxtenh-master/build$ imgtxtenh
imgtxtenh: error: input image required
Usage: imgtxtenh [options] <in_img> [out_img (def.=png:-)]

 -u (mm|pixels)  Units for ALL distance parameters (def.=pixels)
 -d density      Specify the image density in pixels per cm (def.=false)
 -t type:string  Local enhancement type: sauvola, sauvolaSdMax, wolf (def.=sauvola)
 -w width:float  Window width for local enhancement (def.=80px|10mm)
 -k mfct:float   Local enhancement mean threshold factor (def.=0.2)
 -s sfct:float   Local enhancement threshold slope factor (def.=0.5)
 -S [r]sat:float Contrast stretch [optionally per region] saturating sat% of pixels (def.=false)
 -A              Use input image alpha channel as processing mask (def.=true)
 -M mfile        Read separate processing mask image (def.=false)
 -P pfile        Post-processing mask image (def.=false)
 -N              Negate mask images (def.=false)
 -a              Save processing mask as alpha channel in output image (def.=false)
 -r small:float  Area limit for small component removal (def.=6px^2|0.16mm^2)
 -R lengths      Protect faint strokes by 4-directional RLSA: '-', '|', '/' and '\' (def.=2.4,2.4,2.4,2.4px|0.4,0.4,0.4,0.4mm|)
                 lengths are 1 to 4 floats separated by commas
 -p              Save images imgtxtenh_*.png of processing steps (def.=false)
 -l lfile        Logging to 'lfile' (def.=stderr)
 -V (-|+|level)  Set verbosity level (def.=1)
 -h              Print this usage information and exit
 -v              Print version and exit

imgtxtenh: revision 248 (2017-12-09 08:31:46 +0100)

That's all

**Comment by zvezdochiot** [comment]
@zengqi0730 say> I solved

You just didn't have imagemagick-dev on the system. No more.
```
sudo make install
```
added `*.h` files `imagemagick` to you system.

**Comment by mauvilsa** [comment]
@zengqi0730 could you please give details about the operating system you are using, just for future reference if someone else comes here looking for answers. It is true that the best solution is to use your operating system's package manager to install the dev package as @zvezdochiot commented. Still, from what I understand in the original question it seems like the cmake ran successfully, which I find weird since I guess this shouldn't have happened if you didn't have the header files installed.
